version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petclinic

  adminer:
    image: adminer
    restart: always
    depends_on:
      - "db"
    ports:
      - 8686:8080

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672